### ISSUE TITLE
Avoid swallowing exceptions when possible

### ISSUE THREAD

**Issue by tmecklem** [atuley/twitter#9]
https://github.com/atuley/twitter/blob/408f0de11fb6391678026558c5b5d4b98418d862/app/controllers/application_controller.rb#L20

The `find` method throws `RecordNotFound` if id can't be located, but the `find_by` method does not. I recommend replacing this with `find_by(id: session[:user_id])`.

**Comment by atuley** [comment]
Thanks again for your feedback on this exercise! I'm hoping we get to pair again in the near future!
